### ISSUE TITLE
issue in adding dependency in pubspec.yaml

### ISSUE THREAD

**Issue by Selvam-bestea** [jffiorillo/dart-countries-states#1]
i had added
  dart_countries_states: ^0.0.8
to my pubspec.yaml and proceed with pub get but it result in error

**Comment by jffiorillo** [comment]
Can you show me the error logs?

**Comment by cyberpwnn** [comment]
@jffiorillo update http see #2 please

**Comment by jffiorillo** [comment]
Thank you for the PR 👍
